name: CronCapture

on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"
jobs:
  capture:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        timeout-minutes: 5
        with:
          source: https://store-jp.nintendo.com/software/ranking/
          destination: screenshot.png
          #full-page: true
          timeout: 180
          width: 1000
          height: 3000
          scale-factor: 1
#      - name: save capture image
#        uses: actions/upload-artifact@v2
#        with:
#          name: capture image
#          path: ./screenshot.png
